# Generated by Django 4.2.6 on 2023-11-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="garage",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="garage",
            name="start_time",
        ),
    ]
