# Generated by Django 4.2.6 on 2023-11-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_garage_end_time_remove_garage_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="GarageWeekDay",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.garageweekday",
            ),
            preserve_default=False,
        ),
    ]
