# Generated by Django 4.2.6 on 2023-10-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_name_user_verify_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verify",
        ),
    ]
